export const tableStyles = {
  container: 'rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden',
  header: 'bg-gray-50 dark:bg-gray-800',
  headText: 'font-bold text-slate-200 dark:text-slate-300',
  row: 'bg-white dark:bg-gray-900 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors',
  codeCell: 'font-mono text-white',
  plateCell: 'font-mono font-semibold text-gray-900 dark:text-white',
  textCell: 'text-sm text-gray-600 dark:text-gray-400 font-medium',
  mutedCell: 'text-gray-600 dark:text-gray-400',
  emptyCell: 'h-32 text-center',
  emptyState: 'flex flex-col items-center justify-center text-gray-500 dark:text-gray-400',
  actionBlue: 'hover:bg-blue-100 dark:hover:bg-blue-900/50 rounded-lg text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300',
  actionCyan: 'hover:bg-cyan-100 dark:hover:bg-cyan-900/50 rounded-lg text-cyan-600 dark:text-cyan-400 hover:text-cyan-700 dark:hover:text-cyan-300',
  actionRed: 'hover:bg-red-100 dark:hover:bg-red-900/50 rounded-lg text-red-600 dark:text-red-400 hover:text-red-700 dark:hover:text-red-300',
  actionsHead: 'text-center w-[180px] min-w-[180px]',
  actionsCell: 'w-[180px] min-w-[180px]',
  actionsGroup: 'mx-auto flex w-fit items-center justify-center gap-1',
  loadingSpinnerBlue: 'w-8 h-8 animate-spin text-blue-600 dark:text-blue-400',
  loadingSpinnerCyan: 'w-8 h-8 animate-spin text-cyan-600 dark:text-cyan-400',
} as const;
